### ISSUE TITLE
Virus Detected (Fake?) in Windows

### ISSUE THREAD

**Issue by jberries** [reda-marzouk608/scrape-master#1]
In Windows 11, when you 'Download Zip' form github, Windows Defender flags the zip file as a virus and blocks it. Interestingly, however, Defender does not block the files when using 'git clone' in PowerShell.

**Comment by reda-marzouk608** [comment]
The only file I can think of that will trigger the windows defender is the chromedriver.
Otherwise you can explore all the other .py files to make sure they are valid.
