### ISSUE TITLE
Pagination and Attended Mode are disabled when multiple URLs are entered.

### ISSUE THREAD

**Issue by Kyrpel** [reda-marzouk608/scrape-master#2]
when i place multiple urls sapareted by spaces i get the error "Pagination and Attended Mode are disabled when multiple URLs are entered."

\streamlit_app.py", line 110, in <module>
    st.session_state['pagination_details'] = pagination_details
NameError: name 'pagination_details' is not defined

**Comment by wedontdozero** [comment]
You need to add the pagination_details = "" on line 90 of steamlit_app.py @Kyrpel 
```
else:
    # Multiple URLs entered; disable Pagination and Attended Mode
    use_pagination = False
    attended_mode = False
    pagination_details = ""  # Initialize with an empty string
    # Inform the user
    st.sidebar.info("Pagination and Attended Mode are disabled when multiple URLs are entered.")
```
